project:
  type: book
  output-dir: docs
  execute-dir: project

book:
  title: "Mendelian Randomization Tutorial"
  author: "Shea J Andrews"
  date: "2/2/2023"
  repo-url: https://github.com/AndrewsLabUCSF/MR-tutorial
  sharing: [twitter]
  chapters:
    - index.qmd
    - scripts/intro.qmd
    - scripts/sumstats.qmd
    - scripts/references.qmd

bibliography: references.bib

format:
  html:
    theme: yeti
    number-depth: 1


editor: visual

