project:
  type: book
  output-dir: docs
  execute-dir: project

book:
  title: "Mendelian Randomization Tutorial"
  author: "Shea J Andrews"
  date: "2/2/2023"
  repo-url: https://github.com/AndrewsLabUCSF/MR-tutorial
  sharing: [twitter]
  chapters:
    - index.qmd
    - part: scripts/intro.qmd
      chapters:
      - scripts/phenotypes.qmd
      - scripts/sumstats.qmd
    - part: scripts/methods.qmd
      chapters:
        - scripts/mr_harmonization.qmd
        - scripts/mr_harmonization_II.qmd
        - scripts/mr.qmd
        - scripts/radial_mr.qmd
        - scripts/mvmr.qmd
        - scripts/lhc_mr.qmd
    - scripts/references.qmd

  

bibliography: references.bib

format:
  html:
    theme: yeti
    number-depth: 1


editor: visual

